<?php namespace ProcessWire;

/**
 * An Inputfield for handling single line "text" form inputs
 *
 * @property string $type Input type (typically "text")
 * @property int $size Size of input or 0 for full width
 * @property int $minlength Minimum allowed length of value (usually combined with 'required' option)
 * @property int $maxlength Maximum allowed length of value
 * @property string $placeholder Placeholder attribute text
 * @property string $pattern HTML5 pattern attribute
 * @property string $initValue Optional initial/default value
 * @property bool $stripTags Should HTML tags be stripped from value?
 * @property bool $useLanguages When combined with multi-language support, setting this to true will provide one input per language. Get/set each language value with the "value[languageID]" property, and just "value" for default language.
 * @property bool|int $requiredAttr When combined with "required" option, this also makes it use the HTML5 "required" attribute. (default=false)
 * @property int $showCount Show a character counter (1) or word counter (2) or neither (0). Recommended value is 1 when using minlength or maxlength.
 *
 *
 */
class InputfieldFormCancelButton extends InputfieldFormButton {

	public static function getModuleInfo() {
		return array(
			'title' => __('Form Cancel Button', __FILE__), // Module Title
			'summary' => __('Button for cancel action', __FILE__), // Module Summary
			'version' => 100,
			'permanent' => false,
			);
	}
}
